### ISSUE TITLE
`migration_template': wrong number of arguments (given 1, expected 2..3)

### ISSUE THREAD

**Issue by k1ife** [kmmndr/geonames_dump#3]
Hi, i have some problems with "rails generate geonames_dump:install"

`/home/user/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/generators/migration.rb:54:in 'migration_template': wrong number of arguments (given 1, exp 2..3) (ArgumentError)

```
    from /home/user/.rvm/gems/ruby-2.3.0/gems/geonames_dump-0.0.6/lib/generators/geonames_dump/install_generator.rb:20:in 'block in copy_migrations_f

    from /home/user/.rvm/gems/ruby-2.3.0/gems/geonames_dump-0.0.6/lib/generators/geonames_dump/install_generator.rb:13:in 'each'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/geonames_dump-0.0.6/lib/generators/geonames_dump/install_generator.rb:13:in 'copy_migrations_files'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in 'block in invoke_all'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in 'each'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in 'map'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in 'invoke_all'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in 'dispatch'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/generators.rb:157:in 'invoke'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/generate.rb:13:in '<top (required)>'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in 'require'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in 'block in require'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in 'load_dependency'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in 'require'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:123:in 'require_command!'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:130:in 'generate_or_destroy'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:50:in 'generate'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in 'run_command!'

    from /home/user/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in '<top (required)>'
    from bin/rails:9:in 'require'

    from bin/rails:9:in '<main>'`
```

So i can't do the rest part "rake geonames_dump:install"

rake aborted!
NameError: uninitialized constant GeonamesCountry
/home/user/.rvm/gems/ruby-2.3.0/gems/geonames_dump-0.0.6/lib/tasks/truncate.rake:29:in 'block (3 levels) in <top (required)>'
/home/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in 'eval'
/home/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in '<main>'
Tasks: TOP => geonames_dump:install => geonames_dump:truncate:all => geonames_dump:truncate:countries

**Comment by k1ife** [comment]
Rails 4.2.5
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by groe** [comment]
I'm having the same problem

**Comment by kmmndr** [comment]
Hi,
Sorry for the delay of my answer and thank you for pointing on this bug.
Rails migration API has changed a little bit.
You may find a new release of this gem on rubygems.

**Comment by nikoma** [comment]
The problem has returned in Rails 5.1.x - migration_template': wrong number of arguments (given 1, expected 2..3)
